language: go

sudo: false

go:
  - tip

before_install:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./...
  - go test -v ./...
  - go test -coverprofile=parser.coverprofile ./parser
  - go test -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
